### ISSUE TITLE
Checklist: Confluence storage format conversions

### ISSUE THREAD

**Issue by farbodsz** [farbodsz/pandoc-confluence#1]
## Checklist

The main set of features that need to be added (according to Confluence documentation) are:

- [x] Inline text formatting
  - [x] Strike-through
- [ ] Character escaping
- [ ] List formats
  - [ ] Task list
- [ ] Links
  - [ ] To another Confluence page
  - [ ] To an attachment
  - [ ] To an external site
  - [ ] To an anchor (same page)
  - [ ] With embedded image as body
  - [ ] Error on any markup not permitted in Confluence link bodies
- [ ] Images
  - [x] Attached image
  - [x] External image
  - [ ] Image attributes
 - [ ] Code blocks
   - [x] Simple
   - [ ] With all the Confluence options
 - [ ] Block text formats
   - [ ] Note
   - [ ] Info
   - [ ] Tip
   - [ ] Warning
   - [ ] Expandable
 - [ ] Table of contents
   - [ ] Basic
   - [ ] With all the Confluence options
 - [ ] Special inline text formats
   - [ ] User mentions
   - [ ] JIRA link
   - [ ] Status badge
